#! /bin/sh

# Prepare dtf-postgresql distribution tarballs for all supported distros.
# Copyright (C) 2015 Red Hat, Inc.
# Written by Pavel Raiskup.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

: ${DTF_GEN=dtf-gen}

name=dtf-postgresql
version=0.1
distros='
    fedora-22-x86_64
    fedora-23-x86_64
    fedora-rawhide-x86_64
'

tmpdir=`mktemp -d /tmp/$name-XXXXXX` || exit 1

for distro in $distros
do
    echo "preparing $distro"
    (
    tarballdir=$name-$distro-$version
    export outputdir=$tmpdir/$tarballdir
    mkdir -p "$outputdir" || exit 1
    "$DTF_GEN" --distro "$distro" || exit 1
    cd "$outputdir/.."
    tar -caf "$tarballdir".tar.xz "$tarballdir" || exit 1
    ) || exit 1
done
echo "done at $tmpdir"
